matrix:
  include:
    - os: linux
      sudo: required
      env: BUILDARCH=x64
      dist: trusty
    # - os: linux
    #   sudo: required
    #   env: BUILDARCH=arm64
    #   dist: trusty
    # - os: linux
    #   sudo: required
    #   env: BUILDARCH=arm
    #   dist: trusty
    - os: osx
    - os: windows

language: node_js
node_js: '13'

before_script:
  ./scripts/build.sh
script:
  ./scripts/testAll.sh
# deploy:
#   provider: releases
#   api_key:
#     secure: "cbm324krGo1pM4jgsLbPV5YxHqycbBXEIIiDLvhmZPQWFb+g0hoSiPCu4xHpAj+0IqARle7Ufrao6TY5A5m2iMrx0wWNPBXcsOc286F+wgLW3EM2wHKr5J/uMBYQeOkYscK66r6tiBByrfvMHNS8MoZZdGdB+0RDyXaBE9lHrD1KizmSAYjkIPyNvvVxdV2BrqaEqHgCRcWGyyl8XOfoZ3WVQ54Y3lc7NLfnelptmkrytex15WZMChYxASbJc0D/mFNC+MfN6amHouiCj4gPNyMjxCiLz6QrV0YEwg0uhnRqlDXkNcz0pCQHf9apew7heVnzjvP9hhRGAh7Q9yK5B2t9Bjm6k+2c/pyq0IhlPuoDzvzXmCQRkhdB5Eroi+EpJxCYxQdTOmjS31yCSZAq53BgDhkRDjkjF5qtBvLy6CE2TG16dpzqzBCYP+yd7qdtvkKpCsQIRsA4rqghHsrRhnRgZiwawClVIW0pHE17lscjFSdSnXPzqopT5flw8+1iuVvaeGvayv2fV/UOOQ4YkHTEQ+Q0NEQe1MRqaWw/YXq1aUNupDw8KfqOd3d0K4OFw+em6etL+tKPRvwicQGhAA6+DJCVxg0d75Ain3Qkg0p6xQgrjLeNHoWTdJIiKd4uJkWADGH99Sh5qa1O06KbarkYlFw7a2AJQ4gdUhcujIQ="
#   file_glob: true
#   file: 
#     - ./vault/**/*
#   skip_cleanup: 'true'
#   on:
#     all_branches: true
#     tags: true