area.onboard:
  - '- \[ ?(?:x|X) ?\] **Onboard.**'
area.create:
  - '- \[ ?(?:x|X) ?\] **Create.**'
area.retrieve:
  - '- \[ ?(?:x|X) ?\] **Retrieve.**'
area.structure:
  - '- \[ ?(?:x|X) ?\] **Structure.**'
area.publish:
  - '- \[ ?(?:x|X) ?\] **Publish.**'
area.misc:
  - '- \[ ?(?:x|X) ?\] Misc'
type.bug:
  - '- \[ ?(?:x|X) ?\] Bug'
type.enhancement:
  - '- \[ ?(?:x|X) ?\] Enhancement of an existing Feature.'
type.feature:
  - '- \[ ?(?:x|X) ?\] Request of a new feature.'
status.triage-needed:
  - "(?:.*)"

